data = [
    ["AFGHANISTAN", "AFN", "971"],
    ["ALBANIA", "ALL", "008"],
    ["ALGERIA", "DZD", "012"],
    ["AMERICAN SAMOA", "USD", "840"],
    ["ANDORRA", "EUR", "978"],
    ["ANGOLA", "AOA", "973"],
    ["ANGUILLA", "XCD", "951"],
    ["ANTARCTICA", "", ""],
    ["ANTIGUA AND BARBUDA", "XCD", "951"],
    ["ARGENTINA", "ARS", "032"],
    ["ARMENIA", "AMD", "051"],
    ["ARUBA", "AWG", "533"],
    ["AUSTRALIA", "AUD", "036"],
    ["AUSTRIA", "EUR", "978"],
    ["AZERBAIJAN", "AZN", "944"],
    ["BAHAMAS (THE)", "BSD", "044"],
    ["BAHRAIN", "BHD", "048"],
    ["BANGLADESH", "BDT", "050"],
    ["BARBADOS", "BBD", "052"],
    ["BELARUS", "BYN", "933"],
    ["BELGIUM", "EUR", "978"],
    ["BELIZE", "BZD", "084"],
    ["BENIN", "XOF", "952"],
    ["BERMUDA", "BMD", "060"],
    ["BHUTAN", "BTN", "064"],
    ["BHUTAN", "INR", "356"],
    ["BOLIVIA (PLURINATIONAL STATE OF)", "BOB", "068"],
    ["BOLIVIA (PLURINATIONAL STATE OF)", "BOV", "984"],
    ["BONAIRE, SINT EUSTATIUS AND SABA", "USD", "840"],
    ["BOSNIA AND HERZEGOVINA", "BAM", "977"],
    ["BOTSWANA", "BWP", "072"],
    ["BOUVET ISLAND", "NOK", "578"],
    ["BRAZIL", "BRL", "986"],
    ["BRITISH INDIAN OCEAN TERRITORY (THE)", "USD", "840"],
    ["BRUNEI DARUSSALAM", "BND", "096"],
    ["BULGARIA", "BGN", "975"],
    ["BURKINA FASO", "XOF", "952"],
    ["BURUNDI", "BIF", "108"],
    ["CABO VERDE", "CVE", "132"],
    ["CAMBODIA", "KHR", "116"],
    ["CAMEROON", "XAF", "950"],
    ["CANADA", "CAD", "124"],
    ["CAYMAN ISLANDS (THE)", "KYD", "136"],
    ["CENTRAL AFRICAN REPUBLIC (THE)", "XAF", "950"],
    ["CHAD", "XAF", "950"],
    ["CHILE", "CLF", "990"],
    ["CHILE", "CLP", "152"],
    ["CHINA", "CNY", "156"],
    ["CHRISTMAS ISLAND", "AUD", "036"],
    ["COCOS (KEELING) ISLANDS (THE)", "AUD", "036"],
    ["COLOMBIA", "COP", "170"],
    ["COLOMBIA", "COU", "970"],
    ["COMOROS (THE)", "KMF", "174"],
    ["CONGO (THE DEMOCRATIC REPUBLIC OF THE)", "CDF", "976"],
    ["CONGO (THE)", "XAF", "950"],
    ["COOK ISLANDS (THE)", "NZD", "554"],
    ["COSTA RICA", "CRC", "188"],
    ["CROATIA", "HRK", "191"],
    ["CUBA", "CUC", "931"],
    ["CUBA", "CUP", "192"],
    ["CURAÇAO", "ANG", "532"],
    ["CYPRUS", "EUR", "978"],
    ["CZECH REPUBLIC (THE)", "CZK", "203"],
    ["CÔTE D'IVOIRE", "XOF", "952"],
    ["DENMARK", "DKK", "208"],
    ["DJIBOUTI", "DJF", "262"],
    ["DOMINICA", "XCD", "951"],
    ["DOMINICAN REPUBLIC (THE)", "DOP", "214"],
    ["ECUADOR", "USD", "840"],
    ["EGYPT", "EGP", "818"],
    ["EL SALVADOR", "USD", "840"],
    ["EQUATORIAL GUINEA", "XAF", "950"],
    ["ERITREA", "ERN", "232"],
    ["ESTONIA", "EUR", "978"],
    ["ESWATINI", "SZL", "748"],
    ["ETHIOPIA", "ETB", "230"],
    ["EUROPEAN UNION", "EUR", "978"],
    ["FALKLAND ISLANDS (THE) [MALVINAS]", "FKP", "238"],
    ["FAROE ISLANDS (THE)", "DKK", "208"],
    ["FIJI", "FJD", "242"],
    ["FINLAND", "EUR", "978"],
    ["FRANCE", "EUR", "978"],
    ["FRENCH GUIANA", "EUR", "978"],
    ["FRENCH POLYNESIA", "XPF", "953"],
    ["FRENCH SOUTHERN TERRITORIES (THE)", "EUR", "978"],
    ["GABON", "XAF", "950"],
    ["GAMBIA (THE)", "GMD", "270"],
    ["GEORGIA", "GEL", "981"],
    ["GERMANY", "EUR", "978"],
    ["GHANA", "GHS", "936"],
    ["GIBRALTAR", "GIP", "292"],
    ["GREECE", "EUR", "978"],
    ["GREENLAND", "DKK", "208"],
    ["GRENADA", "XCD", "951"],
    ["GUADELOUPE", "EUR", "978"],
    ["GUAM", "USD", "840"],
    ["GUATEMALA", "GTQ", "320"],
    ["GUERNSEY", "GBP", "826"],
    ["GUINEA", "GNF", "324"],
    ["GUINEA-BISSAU", "XOF", "952"],
    ["GUYANA", "GYD", "328"],
    ["HAITI", "HTG", "332"],
    ["HAITI", "USD", "840"],
    ["HEARD ISLAND AND McDONALD ISLANDS", "AUD", "036"],
    ["HOLY SEE (THE)", "EUR", "978"],
    ["HONDURAS", "HNL", "340"],
    ["HONG KONG", "HKD", "344"],
    ["HUNGARY", "HUF", "348"],
    ["ICELAND", "ISK", "352"],
    ["INDIA", "INR", "356"],
    ["INDONESIA", "IDR", "360"],
    ["IRAN (ISLAMIC REPUBLIC OF)", "IRR", "364"],
    ["IRAQ", "IQD", "368"],
    ["IRELAND", "EUR", "978"],
    ["ISLE OF MAN", "GBP", "826"],
    ["ISRAEL", "ILS", "376"],
    ["ITALY", "EUR", "978"],
    ["JAMAICA", "JMD", "388"],
    ["JAPAN", "JPY", "392"],
    ["JERSEY", "GBP", "826"],
    ["JORDAN", "JOD", "400"],
    ["KAZAKHSTAN", "KZT", "398"],
    ["KENYA", "KES", "404"],
    ["KIRIBATI", "AUD", "036"],
    ["KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)", "KPW", "408"],
    ["KOREA (THE REPUBLIC OF)", "KRW", "410"],
    ["KUWAIT", "KWD", "414"],
    ["KYRGYZSTAN", "KGS", "417"],
    ["LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)", "LAK", "418"],
    ["LATVIA", "EUR", "978"],
    ["LEBANON", "LBP", "422"],
    ["LESOTHO", "LSL", "426"],
    ["LIBERIA", "LRD", "430"],
    ["LIBYA", "LYD", "434"],
    ["LIECHTENSTEIN", "CHF", "756"],
    ["LITHUANIA", "EUR", "978"],
    ["LUXEMBOURG", "EUR", "978"],
    ["MACAO", "MOP", "446"],
    ["MADAGASCAR", "MGA", "969"],
    ["MALAWI", "MWK", "454"],
    ["MALAYSIA", "MYR", "458"],
    ["MALDIVES", "MVR", "462"],
    ["MALI", "XOF", "952"],
    ["MALTA", "EUR", "978"],
    ["MARSHALL ISLANDS (THE)", "USD", "840"],
    ["MARTINIQUE", "EUR", "978"],
    ["MAURITANIA", "MRU", "929"],
    ["MAURITANIA", "MRO", "478"],
    ["MAURITIUS", "MUR", "480"],
    ["MAYOTTE", "EUR", "978"],
    ["MEXICO", "MXN", "484"],
    ["MICRONESIA (FEDERATED STATES OF)", "USD", "840"],
    ["MOLDOVA (THE REPUBLIC OF)", "MDL", "498"],
    ["MONACO", "EUR", "978"],
    ["MONGOLIA", "MNT", "496"],
    ["MONTENEGRO", "EUR", "978"],
    ["MONTSERRAT", "XCD", "951"],
    ["MOROCCO", "MAD", "504"],
    ["MOZAMBIQUE", "MZN", "943"],
    ["MYANMAR", "MMK", "104"],
    ["NAMIBIA", "NAD", "516"],
    ["NAURU", "AUD", "036"],
    ["NEPAL", "NPR", "524"],
    ["NETHERLANDS (THE)", "EUR", "978"],
    ["NEW CALEDONIA", "XPF", "953"],
    ["NEW ZEALAND", "NZD", "554"],
    ["NICARAGUA", "NIO", "558"],
    ["NIGER (THE)", "XOF", "952"],
    ["NIGERIA", "NGN", "566"],
    ["NIUE", "NZD", "554"],
    ["NORFOLK ISLAND", "AUD", "036"],
    ["NORTHERN MARIANA ISLANDS (THE)", "USD", "840"],
    ["NORWAY", "NOK", "578"],
    ["OMAN", "OMR", "512"],
    ["PAKISTAN", "PKR", "586"],
    ["PALAU", "USD", "840"],
    ["PALESTINE, STATE OF", "ILS", "376"],
    ["PANAMA", "PAB", "590"],
    ["PANAMA", "USD", "840"],
    ["PAPUA NEW GUINEA", "PGK", "598"],
    ["PARAGUAY", "PYG", "600"],
    ["PERU", "PEN", "604"],
    ["PHILIPPINES (THE)", "PHP", "608"],
    ["PITCAIRN", "NZD", "554"],
    ["POLAND", "PLN", "985"],
    ["PORTUGAL", "EUR", "978"],
    ["PUERTO RICO", "USD", "840"],
    ["QATAR", "QAR", "634"],
    ["REPUBLIC OF NORTH MACEDONIA", "MKD", "807"],
    ["ROMANIA", "RON", "946"],
    ["RUSSIAN FEDERATION (THE)", "RUB", "643"],
    ["RWANDA", "RWF", "646"],
    ["RÉUNION", "EUR", "978"],
    ["SAINT BARTHÉLEMY", "EUR", "978"],
    ["SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "SHP", "654"],
    ["SAINT KITTS AND NEVIS", "XCD", "951"],
    ["SAINT LUCIA", "XCD", "951"],
    ["SAINT MARTIN (FRENCH PART)", "EUR", "978"],
    ["SAINT PIERRE AND MIQUELON", "EUR", "978"],
    ["SAINT VINCENT AND THE GRENADINES", "XCD", "951"],
    ["SAMOA", "WST", "882"],
    ["SAN MARINO", "EUR", "978"],
    ["SAO TOME AND PRINCIPE", "STN", "930"],
    ["SAO TOME AND PRINCIPE", "STD", "678"],
    ["SAUDI ARABIA", "SAR", "682"],
    ["SENEGAL", "XOF", "952"],
    ["SERBIA", "RSD", "941"],
    ["SEYCHELLES", "SCR", "690"],
    ["SIERRA LEONE", "SLL", "694"],
    ["SINGAPORE", "SGD", "702"],
    ["SINT MAARTEN (DUTCH PART)", "ANG", "532"],
    ["SLOVAKIA", "EUR", "978"],
    ["SLOVENIA", "EUR", "978"],
    ["SOLOMON ISLANDS", "SBD", "090"],
    ["SOMALIA", "SOS", "706"],
    ["SOUTH AFRICA", "ZAR", "710"],
    ["SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "GBP", "826"],
    ["SOUTH SUDAN", "SSP", "728"],
    ["SPAIN", "EUR", "978"],
    ["SRI LANKA", "LKR", "144"],
    ["SUDAN (THE)", "SDG", "938"],
    ["SURINAME", "SRD", "968"],
    ["SVALBARD AND JAN MAYEN", "NOK", "578"],
    ["SWEDEN", "SEK", "752"],
    ["SWITZERLAND", "CHF", "756"],
    ["SYRIAN ARAB REPUBLIC", "SYP", "760"],
    ["TAIWAN (PROVINCE OF CHINA)", "TWD", "901"],
    ["TAJIKISTAN", "TJS", "972"],
    ["TANZANIA, UNITED REPUBLIC OF", "TZS", "834"],
    ["THAILAND", "THB", "764"],
    ["TIMOR-LESTE", "USD", "840"],
    ["TOGO", "XOF", "952"],
    ["TOKELAU", "NZD", "554"],
    ["TONGA", "TOP", "776"],
    ["TRINIDAD AND TOBAGO", "TTD", "780"],
    ["TUNISIA", "TND", "788"],
    ["TURKEY", "TRY", "949"],
    ["TURKMENISTAN", "TMT", "934"],
    ["TURKS AND CAICOS ISLANDS (THE)", "USD", "840"],
    ["TUVALU", "AUD", "036"],
    ["UGANDA", "UGX", "800"],
    ["UKRAINE", "UAH", "980"],
    ["UNITED ARAB EMIRATES (THE)", "AED", "784"],
    ["UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)", "GBP", "826"],
    ["UNITED STATES MINOR OUTLYING ISLANDS (THE)", "USD", "840"],
    ["UNITED STATES OF AMERICA (THE)", "USD", "840"],
    ["URUGUAY", "UYU", "858"],
    ["UZBEKISTAN", "UZS", "860"],
    ["VANUATU", "VUV", "548"],
    ["VENEZUELA (BOLIVARIAN REPUBLIC OF)", "VES", "928"],
    ["VENEZUELA (BOLIVARIAN REPUBLIC OF)", "VEF", "937"],
    ["VIET NAM", "VND", "704"],
    ["VIRGIN ISLANDS (BRITISH)", "USD", "840"],
    ["VIRGIN ISLANDS (U.S.)", "USD", "840"],
    ["WALLIS AND FUTUNA", "XPF", "953"],
    ["WESTERN SAHARA", "MAD", "504"],
    ["WESTERN SAHARA", "DZD", "012"],
    ["YEMEN", "YER", "886"],
    ["ZAMBIA", "ZMW", "967"],
    ["ZIMBABWE", "ZWL", "932"]
]
# Create an empty dictionary to store the country codes and numbers
code_number_lookup = {}

for row in data:
    code = row[1]
    number = row[2]
    if number and number not in code_number_lookup:
        code_number_lookup[number] = code
